# Generated by Django 5.0.6 on 2024-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_laptop_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='screen_resolution',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='processor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_resolution',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
