# Generated by Django 5.0.6 on 2024-05-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
