# Generated by Django 5.0.6 on 2024-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_monitor_screen_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='panel_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='television',
            name='screen_resolution',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
