# Generated by Django 5.0.6 on 2024-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_television_panel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='os_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_resolution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
