# Generated by Django 5.0.6 on 2024-05-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_earbuds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Earbuds',
        ),
    ]
