# Generated by Django 5.0.6 on 2024-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_earbuds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(upload_to='products/')),
                ('MSRP', models.FloatField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('wireless', models.BooleanField()),
                ('battery_life', models.FloatField(blank=True, null=True)),
                ('active_noise_cancellation', models.BooleanField()),
                ('mic', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(upload_to='products/')),
                ('MSRP', models.FloatField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('wireless', models.BooleanField()),
                ('battery_life', models.FloatField(blank=True, null=True)),
                ('size', models.CharField(choices=[('60%', '60%'), ('68%', '68%'), ('70%', '70%'), ('80%', '80%'), ('100%', '100%')], max_length=10)),
                ('key_switches', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(upload_to='products/')),
                ('MSRP', models.FloatField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('battery_life', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True)),
                ('screen_size', models.FloatField(blank=True)),
                ('screen_resolution', models.CharField(max_length=15)),
                ('ports_available', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(upload_to='products/')),
                ('MSRP', models.FloatField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('wireless', models.BooleanField()),
                ('polling_rate', models.IntegerField()),
                ('battery_life', models.FloatField(blank=True, null=True)),
                ('buttons_count', models.IntegerField()),
                ('dpi', models.IntegerField()),
                ('weight', models.FloatField()),
                ('ergonomics', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(upload_to='products/')),
                ('MSRP', models.FloatField(blank=True)),
                ('release_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('battery_life', models.FloatField(blank=True)),
                ('charging_speed', models.IntegerField(blank=True)),
                ('os_version', models.CharField(max_length=50)),
                ('software_updates_years', models.IntegerField(blank=True)),
                ('size', models.IntegerField(blank=True)),
                ('screen_resolution', models.CharField(max_length=15)),
                ('screen_refresh_rate', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
