# Generated by Django 5.0.6 on 2024-05-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_earbuds_msrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='buttons_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='dpi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='ergonomics',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='polling_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='wireless',
            field=models.BooleanField(null=True),
        ),
    ]
