# Generated by Django 5.0.6 on 2024-05-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_mouse_buttons_count_alter_mouse_dpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earbuds',
            name='active_noise_cancellation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earbuds',
            name='wireless',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='active_noise_cancellation',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='mic',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='headphones',
            name='wireless',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='key_switches',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='size',
            field=models.CharField(choices=[('60%', '60%'), ('68%', '68%'), ('70%', '70%'), ('80%', '80%'), ('100%', '100%')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='wireless',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ports_available',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_resolution',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery_life',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='charging_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='os_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_refresh_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_resolution',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='software_updates_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
