import os
import sys
import time
import django
import re
import google.generativeai as genai
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()
from api.models.product import Product
from api.models.mouse import Mouse

class Gemini:
    # Setup for google gemini
    GOOGLE_GEMINI_KEY = os.environ.get('GOOGLE_GEMINI_KEY')
    genai.configure(api_key=GOOGLE_GEMINI_KEY)
    model = genai.GenerativeModel('gemini-1.5-flash')
    
    sentiment_query = '''Analyse the sentiment about an electronic product: {name} from the comments below. 
        Give a score out of 10, 10 for most positive. Also give 50 word justification of the score. 
        Format the answer like score:"8"; description:"....."
        Comments: {comments}'''
        
    summerise_query = '''Summerise the reviews about this electronic product: {name}. 
        Want a brief description of the product, then how it performs according to various criteria/things the reviewer liked/disliked
        Keep the langauge fun, simple and neutral
        Minimum 300 words, maximum 450 words.
        Format the answer like summary:".....". In prose, with simple paragraphing
        Reviews: {reviews}'''
        
    def __new__(cls):
        # Overriding default creation of new instance, no point for more than 1 instance
        if not hasattr(cls, 'instance'):
            cls.instance = super(Gemini, cls).__new__(cls)
        return cls.instance

    def analyse_product(self, product:Product):
        name = product.get_name()
        comments = product.get_reddit_comments()
        
        if len(comments) < 5 or len(product.get_justification().split()) > 20:
            return product
        
        query = self.sentiment_query.format(name=name, comments=str(comments))
        
        try:
            response = self.model.generate_content(
                query,
                generation_config=genai.types.GenerationConfig(
                candidate_count=1,
                temperature=1.0)
            )
            
            # Need wait to respect google request limits
            time.sleep(62)
            
            content = re.findall(r'"(.*?)"', response.text)
            score = content[0]
            justification = content[1]
            product.add_score(int(score))
            product.add_justification(justification)
        
        except Exception as e:
            print(e)
        finally:
            print(product)
            product.save()
            return product
    
    def summarise_reviews(self, product:Product):
        name = product.get_name()
        description = product.get_description()
        
        if len(product.get_summary().split()) > 50: return product
        
        query = self.summerise_query.format(name=name, reviews=description)
        
        try:
            response = self.model.generate_content(
                query,
                generation_config=genai.types.GenerationConfig(
                candidate_count=1,
                temperature=1.0)
            )
            
            # Need wait to respect google request limits
            time.sleep(62)
            
            content = response.text.split(':')
            summary = content[1].replace('"', '')
            product.add_summary(summary)
        
        except Exception as e:
            print(e)
        finally:
            print(product)
            product.save()
            return product
        
            
def main():
    ai = Gemini()
    # comments = [
    #         "Oneplus 12, great phone, but destroys the android experience...",
    #         "Hey everyone, I just switched from the p30 pro, which was way ahead of it's time in terms of camera and battery life, to the OnePlus 12, which is incredible in it's own rights, but it's definitely lacking to a point where I feel it brings android a few steps back, mostly because of Oxygen OS 14.\nOxygen OS is very smooth, but lacks the customization that other android phones have. For example:\nWhen customizing your home screen, the ability to move home screens arround isn't possible.\nYour home screen is forced to be the one on the left.\nGoogle discovery cannot be disabled from the left side of the screen (I have seen some posts saying you have to force stop google or whatnot, but that is not a permanent solution)\nThe camera for some unknown reason tends to put a yellowish tint in white rooms. (Probably fixable with a software update 🙏🏼)\nNot all app icons can blend in with the color theme.\nDoesn't have a thems store.\nDon't get me wrong, I love this phone. Amazing charging, great display, IR PLASTER (😍), great cameras. But I still feel it lacks a lot in terms of it's UI. Is it an actual upgrade compared to a 4-5 year old phone like the P30 pro? Yes, a bit. But mostly because this phone has aged and apps are starting to lose support for it's outdated android 10.\nWhat are your thoughts?\nRead more",
    #         "The yellowish tint in photos bothers me as well.",
    #         "Colors in photos is with every brand , hope they fix it. iPhone still has some washed pics. Samsung blues the sky too much and in dark the sky looks gray and not black. Pixel is too contrasty and dark sometimes. OnePlus is yellowish sometimes. At this point, there is no perfect Camera that can satisfy everyone. It's subjective.",
    #         "I actually posted about the same thing, I recently switched from a very outdated Huawei phone (it had Google services tho) to OnePlus. I absolutely love the screen and the battery life and the amazing fast charging or the incredible sounding stereo speakers, but as you said the system does lack some small yet important customization options, while it does have some very awesome features such as material you icons built in the system and colors editor that works across the whole system based on your wallpaper but does not have lock screen clock style changer or no official themes app to begin with. Because of my post OnePlus actually contacted me and they basically said that they'll bring it to the developing team's attention, so fingers crossed they might actually listen and add those missing features to the system.",
    #         "This is why I just use Nova Launcher. No matter which phone I use, I can have it looking how I want it to",
    #         "True, from P30 Pro to Nord 3 OxygenOS 14. UI is not match to the old P30 Pro. Had to use Nova Launcher to get rid of the Google Discovery page.. P30 pro features not on OxygenOS:. Floating navigation dock Auto Hide navigation buttons Lock Screen signature Screen capture file naming convention - in huawei youll know if screen capture was taken on a specific app with their naming convention. Very handy when doing searches. OxygenOS just random numbers.. Optimized status bar icon spacing - OxygenOS too far apart. Has Own calendar app - meaning you can have a local calendar Has own contacts app - meaning, you can have numbers saved own phone. Prefer SwiftKey over GBoard Built.in voice recorder Built.in AR Measure. Can put notes on picture - handy in searching pictures. Nord 3 OxygenOS 14 pros:. Speed - of course if comparing to a 4 year old phone. Has secure keyboard when entering passwords. Side switch to control sounds is very handy but is mechanical so prone to wear and tear. Has community app by default. If no future improvements - next phone will be Honor due to UI.",
    #         "There should be at least 1 ONEPLUS rep on this thread to filter all our woes with Oneplus 12. Currently using it as I type. Still using my s22u as my main phone and this 12 as my work and game phone. The UI is little to be desired and I use MS Launcher as my go to. The good thing with MS Launcher, you can choose which home screen you want to put first and edit it but the problem is swiping left to right is tad too slow even with the animation speed is set to high unless I use the high refresh rate of 120hz, my preferred refresh rate is \"auto\" so when switching back to the stock launcher everything is smooth and snappy with refresh rate set to auto. I'm good with this launcher. Hopefully an update will come soon to rectify this issue. For now, I'll just copy the icons and apps layout from my MS Launcher to the stock launcher. It's quite alot of work but it's gonna be worth it.",
    #         "Yeah hopefully someone is listening. I tried nova and Niagara with no luck. I alway have this second of delay when going back to the home screen.. Here's what I mean:. https://drive.google.com/file/d/12Iqzi8H8gFaNzxcmk8P1Ek0GD8y14IDz/view?usp=drivesdk. Hve you had this problem with the Microsoft launcher?",
    #         "Hey, sorry for late bump on this post but i am a s22u user and was wondering about seeling it for op12. How would you compare the cameras between the two?. My biggest worry is downgrading cameras if i switch...",
    #         "A different launcher like Nova launcher for example can help. I've been using OnePlus phones for the last decade and they've been trending away from their roots pretty much the entire time. The OnePlus One was released with CyanogenMod that later turned into Lineage OS and is what drew me to the OnePlus One in the first place. Unfortunately those days are long gone. Moving towards being a clone of other companies devices seems to be more the goal these days. Unfortunately the options aren't great for those of us who want a highly customizable android experience. It is still possible to root and install custom roms but an out of the box alternative with vanilla android and a switch to turn on and off root privilege for any android device seems like it shouldn't be a hard thing for a phone manufacturer to provide. There's a lot I don't like about the phones now that I won't get into. What I will say is that without some major changes I don't see myself buying another OnePlus phone in the future.",
    #         "Oxygen OS is one of the most customized Android skins available if you compare it with the likes of Google, Motorola, Asus, etc. The fact you are able to use icon packs within the stock launcher is something that most companies don't do for some reason.",
    #         "Oneplus 12 - First impressions!",
    #         "I can't tell much as most of OP12 is already told. Great device with good build quality, excellent screen and very nice camera and its features. But as I tried several phones past year and my expectations were high, OP12 didn't disappointed, here are few observations;\n-haptics are strong and respectfully loud\n-screen is bright and colours are good, seems well bananced\n-external speaker, my personal opinion, rich and loud, I just like mids and voice tones, well balanced stereo\n-OxygeOS, I had Oppo, very similar, reliable and fast, will not disappoint - but a bit more feature mature than Oppo.\n-connectivity GSM and WIFI, stable and strong so far, yet to be tested in less coverage areas -calls, loud and crisp\n-charging, damn fast, and phone is comfortable with normal usage during charge period (I mean, if you cant wait 25mins;)\n-side buttons are well set, nice and clicky - looove right one for sounds\n-cameras, well, I think they finally matured with software processing. I mean, OP12 have better quality photos than S23U(maybe S24U too as they went with similar setup and software)I had for some time. Pair on Pair - only x10 lens on Samsung beats OP12. Now, photos are nice colored, natural, sharpening is discrete, details are preserved like in highlights and in shadows too. Main sensor is superb, wide good enough (big sensor too) and tele awesome, can produce such good derailed images even beyond optical capabilities! And last thing, bokeh blur on this phone, you will fall in love, don't know how they did it, but very natural and with sense of depth. In conclusion, camera setup definitely is not cons here! Whoever said that its not true!!\nRead more",
    #         "Regarding battery, first charge, setup and everything achieved 7h SOT. Pretty much good.. Only one issue I have, can't get YouTube app to work. It starts and just set with loading and thats it for video.",
    #         "YouTube Revanced? Known issue. Only fix is to root your phone and use the Magisk module ",
    #         "I have the CN variant flashed to Global. YT and everything is working fine.",
    #         "Same. But, it really doesn't bother me. Has alternatives.",
    #         "How's the video call quality through the front camera on WhatsApp?. How's the video quality in general?",
    #         "This one I didn't had a chance yet to try, but upcoming days for sure, will update here for WA.. Video in general, to me looks very good. Fluid and detailed, OIS doing good job too. But I am not that much in video, have lot of experience with photos.",
    #         "I heard it's a beast,I have the 11 and it's a beast also,good looking device as well",
    #         "A week with OP12 and can tell, it is great. For price would say there are no better options, for new one, second hand yes. Only I wish OP included at least x5 periscope lens.",
    #         "I just upgraded from a pixel 7.. It is significantly better.. I don't game but the things important to me are significantly better:. Screen way way way better Battery is much better Speaker is better Phone reception is better Phone voice recognition is better, one thing the pixel 7 would do is filter out high pitched voices like my daughter's and she couldn't speak on it with her mother this was very frustrating... Fingerprint reader is better Face recognition is better Camera seems as good/same as pixel 7. The one thing I don't like over the pixel so far is the camera bump is excessively large or at least I think so. Also I hate the volume on top above the power. Would have preferred it reversed.",
    #         "Do you have problems with touch delay towards the curved edges of the screen",
    #         "Disappointed with the OnePlus 12",
    #         "I have been a OnePlus fan for a while now. I have had the OnePlus 3, 6, 7 pro, 8, 8 pro, 9, 10 pro, 11, and now 12.\nDesign: The phone looks and feels good. I like the camera design. While it's very slippery, I have a case on it, so the slippery aspect doesn't affect me.\nCamera: I was honestly surprised how good the camera is, especially the 3x zoom. Colors, details and dynamic range were very good and better than the s23 ultra imo.\nBattery: Amazing. Lasts all day and then some. Charging is so fast it charges to 100% before I'm even done with any task.\nSoftware: here is where I had issues. Oxygen OS is by no means bad, aestheticly. I did hate the media player. Otherwise than that, it looked fine.\nThe issue here is the phone is so capable with SD 8 Gen 3, 16gb RAM, 4.0 UFS storage and 512 gb storage, yet the phone is slow and drops frames?\nIt doesn't matter what I'm doing, I always feel like the phone is slower. In app performance, outside of games, is abysmal. Scrolling is choppy and typing sometimes even lags. I understand OnePlus is limiting the phone so we can get good battery life. However, I hate it. Give me the choice to pick between normal and limited.\nAnd no, high performance mode is not the answer because HPM is now overkill.\nAlso, apps don't stay in memory and any time I enter an app, I have to wait 2-3 seconds before I start scrolling or the frame will drop.\nRead more",
    #         "Try this. Backup you stuff.. Boot into recovery mode, clear the cache and wipe the partition.. Upon completing the setup immediately debloat the device and test it.. If this did not resolve the issue then it might be the flash storage (UFS) that is faulty.",
    #         "Many people are experiencing this, it's a subtle thing phone isn't slow! It's probably a software issue",
    #         "I love when such stuff pops up. oh you have issues with 1000$ device?. just get an egineering degree and extensive rom expertise, instead of returning obviously flawed product.",
    #         "That doesn't sound right or match my experience. I would return it and try to get a new one if you're able to.",
    #         "Something strange is happening with your phone. Mine is super fast. Every app is amazingly fast. Never had a smoother phone in my life. May be you have a virus or some background app that slows you down?",
    #         "Same. Best phone I've ever owned. Upgraded from a Pixel 6 and it's like night and day.",
    #         "Many more software updates to come and You can't expect huge performance gain by Upgrading every year. The difference is very minimal.",
    #         "Btw the apps that show that 2 to 3 second delay are chrome? Mine is mostly chrome, others are instantly scrollable",
    #         "Oxygen OS/Color OS is holding hack oppo and oneplus phones from being great",
    #         "OnePlus high performance mode is literally just restoring the performance they took away from the processor at stock settings. I wish they would get rid of that throttling but as they've done it since the 9, it's here to stay, so I leave high performance mode on all the time.",
    #         "Switching back to S23 Ultra after a week with the Oneplus 12",
    #         "I got the Oneplus 12 because of its DC dimming and higher PWM at lower brightness, but after a week with it, I was itching to switch back to my S23 Ultra. Thoughts:\nNegatives:\nNova Launcher doesn't work smoothly with gesture controls, there's a noticeable lag when I swipe to home. I thought it won't be a big deal, but couldn't stand it after a few days.\nI miss the One Hand Application app for Samsung, that gave me a bunch of side of the screen gesture actions. I tried a few apps off the Google play store but I couldn't find one as reliable.\nI miss the S pen, good for precise actions, remote camera triggers, and the occasional live sketch.\n4a) I found the colors on the Samsung generally more accurate, with the Oneplus giving most photos a warmer tint than irl. Oneplus sometimes seem to have sharper images though, but that might be due to processing. Night photos and videos seem better on the Samsung.\n4b) I also miss the 10x camera, which is great for travel and animal photography.\n4c) No motion photos on the default oneplus camera app. I like the little snippets of video attached to each photo.\n5) One UI just feels more polished as an OS, more finalized and less improvised.\n6) Samsung Pay turns NFC on and off automatically which seems more secure to me.\nPositives\nRead more",
    #         "I have thought about trying OnePlus every year but I either go with Samsung or Google. Just can't pull the trigger one OnePlus. Maybe next year will be the year. My S23U is a beast of a phone. I don't generally care about charging speed or battery life. I am always near a charger if I need one. I never have to worry about running out of space as I have the 512gb. Camera is great as is the massive amount of customizations on it.. I honestly think the camera circle module on the OnePlus 12 is hideous. It should have been centered the way the OnePlus open is. Consistency with quality does concern me with their phones. I trust Samsung, Google and then OnePlus. In that order. But I'm always curious about trying OnePlus.",
    #         "I'd say grab a discounted OnePlus 11 just to try it out. It's very similar to the 12 and the only thing that you're missing out on is wireless charging. It could be something worth trying out, at least until Google finally gets their shit together with Tensor",
    #         "so sad that oneplus switched to coloros",
    #         "yeah pretty much killed the main reason for me to buy a oneplus",
    #         "OxygenOS 9/10 was peak Oneplus, after that they lost their Identity.. OOS11 tried so hard to be like OneUI and OOS12 went full ColorOS.",
    #         "I am so used and relient on Good lock modules and one hand operation gestures that I can't use any other Android phones now, I tried twice already.",
    #         "Is there a OnePlus equivalent to Samsung's Sound Assitant, where i could set the volume for individual apps or/and shoose which apps output to Bluetooth and which play via the speaker?",
    #         "Interesting. In waiting for a OP12 none of the negatives listed here affect me (seemingly) and the positives all seem legit (again for me).",
    #         "Reviewers always seem predisposed to disliking OneUI, but every other OS is missing features (ex. sound assistant, one hand operation+, routines, dual Bluetooth, move all widgets, rearrange app drawer), even PixelUI is starting to add things that are already on Galaxy (type-c display out).",
    #         "Every year I want to try Oneplus and end up buying Samsung. Currently using S23+ & I'm happy with the Samsung software features (Samsung Dex) that I use every day.l & Samsung keyboard.. The main reason I want Oneplus is because of the better display features + more RAM + very fast charging speed & bigger battery.. Finally, I trust Samsung more in terms of software stability.",
    #         "OnePlus 12 review.",
    #         "Coming from an iPhone a couple years ago to a Samsung 22 Ultra to the 23 Ultra and then to the OnePlus 12, I can just say it's the best phone I've ever had. I get 9 hours of screen on time where my S23 Ultra in battery saving mode would get me maybe 7. I think the camera is great, and better than the S23 Ultra, however the wide angle camera is not very good. The screen is amazing, beautiful, detailed and the phone is way comfier to hold. It's great! I have mine rooted with adaway, I have pixel calling and texting features, free unlimited storage, and a great systemwide equalizer among other perks. I definitely recommend this phone. Also if you are having issues with your phone, a factory reset worked to fix it for me. Also optimize all your apps in battery settings.\nEDIT: After a little time actually comparing images and pixel peeping, the S23 ultra does take sharper more detailed images almost every time at 10X and up. If you're going to be wanting a camera for concerts or 10X zoom I would still stick with the S23 ultra. But if you want a great camera and a great performer for a few hundred off..... This is still an amazing phone and I still prefer it over my S23 ultra in almost every way.\nEDIT 2: I completely forgot to mention the Agua Touch tech that makes it so you can type and use the phone as almost perfectly normal even if your fingers are wet and the screen has some drops on it. AMAZING.",
    #         "Excuse me boss but do you have a tutorial on how to root oneplus 12? Thank you",
    #         "Haven't done this for a while, also only on OP9P but it generally goes like this :. unlock bootloader (all your data will be lost) (you can also do this whenever before step 11). Get oxygen updater, set update settings to 'stable (full)'. Wait for next update. update phone. copy the update zip file from the user root directory on the phone onto a computer, unzip, get payload.bin. extract the init_boot.img from payload.bin using payload extractor. copy that init_boot.img to the phone. install magisk. Patch init_boot.img with magisk. Copy patched init_boot.img to your computer. Reboot phone to bootloader. Flash the patched init_boot.img onto your phone using adb platform-tools on your computer. Reboot phone. Enjoy root access",
    #         "It's an amazing device. But I'll be careful with rooting I use my financial apps and it's a security risk just a heads up.",
    #         "Been using mine for a month now. Everything is great I'm getting 6 -7 SOT on max display settings (quad HD and 120Hz). Mostly I am just browsing the web reading articles, some YouTube and A few episodes of TV series/Anime. Few games of Pokemon Unite and a lot of World of Words levels.. Last night, Flud kept my device awake to download my movies it went from 63 to 14% overnight in 8 hours. 5 hours of Flud in the background.. Charging is very fast, by the time I am done with my morning routine(15-25 mins) my phone is up from 25% to almost 90%+.. Performance is smooth, I have all the apps running in the background forever, only during system update I would restart my phone and they would not be in the background. Most of the time they resume from where I left off.. Apps are quick to load, camera shutter speed is fine, camera quality is 8/10. Didn't have extensive opportunity to take pictures of anything.. Faced no bugs or any kind of hardware issue yet, sometimes it gets quite warmer than usual but it's momentarily and leaving it locked for 5 to 10 mins brings it back to normal.",
    #         "Yea its a great phone with Kool hardware and I'm loving it...u rooted ur OP12",
    #         "well, i'm hoping my hardware won't pop any issue and last long,. so far it's a great device, and i don't root",
    #         "Pretty much my experience. Have the OP12 for a month now. The battery life is so great, I started to limit the charge to 80%. Still gets me easily throughout the day. I intend to keep it for at least 4 years (hence charge limit on the battery). The only thing I am missing from my old Samsung/Pixel phones is the photo/video editing tools (like magic eraser and AI tools). Hopefully OnePlus will bring some of those in later SW updates. The current photo editor is a joke in comparison 🙄",
    #         "I think the camera is great, and better than the S23 Ultra. How about zoom shots? I think at 20x-30x the S23 Ultra would be better than OP12, what is your experience?",
    #         "I agree, root just makes this phone even better ",
    #         "The only gripe I have with the phone is that the glass screen protector doesn't work well with it. The fingerprint basically doesn't work when you have glass applied and it can get loose fast because of the edged screen. But I switched to a foil screen protector (ironic because it came with one :') ) and now everything is fine.",
    #         "OnePlus 12 Vs S23 ultra",
    #         "Hi guys, I'm kind of in a confusion of choosing the best within my budget. According to my budget the OnePlus 12 and S23 ultra both of them fit perfectly. But I can choose only one. That's why, I was wondering if anyone here who used or using both of them can help me out. My priorities are: photography, videography, gaming and media consumption also battery :) I hope I can get help here. Thanks everyone",
    #         "I have a Oneplus 12, whereas my sibling who I live with has the S23 Ultra.. When it gets down to it, regarding battery life and performance, the Oneplus 12 wins due to the newer and more efficient Snapdragon 8 Gen 3 SOC(system on chip). So gaming and battery hands down would be better on a Oneplus 12.. But for everything else, be it a cohesive UI, feature rich OS, extreme flagship level photos and videos, those all go to the S23 Ultra. Yes it might be last years' flagship, but Samsung really made sure that the Galaxy S Ultra series are made a cut above the rest.. In conclusion, depending on features in the 2nd or 3rd paragraph. Which one matters to you most?",
    #         "A great camera and a little bit of gaming. I hope Samsung won't disappoint me while I game And thank you so much for your valuable reply",
    #         "Switched from S23 Ultra to OP12, no regrets.. Battery, smoothness, charging speed is way better on OP12. I prefer the camera on oneplus 12 due to Hasselblad color science but that is just my preference, either way both devices are good for photo/video",
    #         "I own both, OP12, hands down. I miss the routines from the 23U, but thats about it. Battery and Camera on OP12 are consistently better than s23U",
    #         "I had the 23ultra and traded it for the OnePlus 12. I LOVE my OnePlus 12. The 23ultra was a good phone but the physical design made it very hard for me to use one handed. The OnePlus is actually a bit bigger but the curved edges and more rounded design makes it so much easier for me to hold and use one handed if I need to. Also was not a huge fan of the camera on the 23ultra. Pics often came out grainy and oversaturated. I also had a Pixel 8 at the time along with the 23ultra and the pixel was superior to the 23ultra in the photos department, IMO. But the OnePlus 12 takes great photos and I've been very satisfied with them so far... And I take a lot of pics. It's fast, everything works great. Fast battery charging is awesome... Like 20 minutes to full charge. The battery lasts me 2 days easily with moderate to heavy use. I'm not a gamer but I use photos, stream about 3 hours of YouTube a day and am on social media pretty consistently and surfing the web frequently. I Love the keyboard. Very intuitive.. fast and accurate. That was another issue I had with the ultra... I made so many typos with that phone.. not sure why. But the OnePlus is definitely my favorite phone of all the phones I've owned so far.",
    #         "And yes... I traded in a more expensive phone for a less expensive phone but it's been so worth it for me. I'm so much happier and settled with the OnePlus than I was with the 23ultra and that very much makes up for the loss of a couple hundred dollars in the trade.",
    #         "While it is a matter of opinion I don't know why people think One UI is better then oxygen. It is significantly worse imo in both performance and design. In part due to the fact it's a heavier UI skin.. Having more complexity and pointless stacked option menus in your OS and duplicate apps like One UI has is imo not an advantage. One UI does not age well either. Samsung phones always suffer from more performance degradation over time than OnePlus phones running Oxygen OS.. While it has improved I still find the look of one UI to be pretty ugly, especially the squarcle icons and the bland menu style, that is a personal preference though.",
    #         "OnePlus 12 for fast charging, great haptics, Dolby Vision, and a great display. S23 Ultra for the camera (especially tele), the ecosystem, consistent and almost bug-free UI, and DeX. Note there's no Dolby Vision on Samsung so unless the content has HDR10+ support too, it might appear dull, especially on stuff like Netflix.",
    #         "OP12 battery life is good, I'm getting 6-7 hours with 80% charging stop option enabled",
    #         "Based on your criteria, the OnePlus is the \"winner\" besides it's camera.. Now ask yourself, is the price difference of a better camera worth the extra hundreds of dollars to you for the Samsung?. Another question you need to ask are you okay giving up camera goodness for insanely fast charging and lower overall cost?. Your response will be valid either way because it's up to your own tastes and a lot of things people are discussing here, such as UX of the Samsung being \"better\" is down to taste.",
    #         "OnePlus 12 - Personal experience and 15 days later review",
    #         "Ello ello! First time OnePlus user here and I'll be sharing my experience on this beauty and a beast (I'll be adding a couple jokes every now and then😋, my bad if you don't like it 😿)\nI've been a long time motorola user (7 years) and had lots of faith in that brand but everyone has a breaking point and so did it. Motorola phones i used has amazing build quality and they were truly solid and had very clean ui experience but that's about it because they sucked in every other department, they'd be good for max 1 year but that's about it. Last year when OnePlus launched in China I was amazed by how beautiful it looked and made up my mind to switch to it and that i did. I pre ordered my OnePlus 12 within 5 minutes of launch. On 30th i received it and i was literally blown away because how beautiful it looked in person 😩😩. I'll try and share almost every aspect of the phone in different paragraphs.\nBuild:\nSolid, beautiful, well balanced, premium. I ordered black variant and although i use a back case whenever i take it off and look at the back it feels like it's going to consume me because it's so bewitching. The starry sky look is mesmerizing. Whoever has looked at it and said one thing \"absolutely beautiful\". Sorry for not including the image without cover, I don't have any(don't wanna take one with trash cam of motorola either)\nDisplay:\nSmoothhhhh and beautiful. Colours look amazing. First time using curved display and I'm loving it. I haven't faced any accidentally touch. Yes some people hate curved display but hey everyone has preference. I'm like how it's also slightly curved at chin and top. Yes, as other people previously mentioned, the brightness isn't as low. Haven't tried auto brightness because i prefer a certain level of it.\nRead more",
    #         "What a cute dog. Did you buy em to match your phone? ❤️. Thanks for the review! What's your opinion on the green?",
    #         "did you buy them to match your phone. LMAOOOOOOOO NO SHE'S 8 YRS OLD",
    #         "Sorry about not answering the question about green variant because i was in game.. I was thinking about going for green but the metal green on camera module seemed bit odd to me so i just went with black",
    #         "You can get round icons by sliding the roundness all to the right",
    #         "OMG thank you so much. I didn't even check there was roundness option. I was able to find it this time because i tapped on square one and then the roundness slider appeared",
    #         "Bro 8hrs with 5 hrs of gaming. I got a OnePlus 12 pre order unit and I'm getting max 8 hrs with really really light usage (Gps off, 5g off, just watching YouTube nd scrolling a Lil bit, low brightness as I'm currently working from home). Idk if I got a faulty unit or not.",
    #         "no, you don't have a faulty unit. the battery on the oneplus 12 really isn't as great as everyone claims. i left home without the charger one time with it and almost came home with zero power and i didn't even use it like that so now i don't trust it i leave with the charger. to be fair i didn't leave the house with 100% battery but with people raving about it the way they are and with me barely using it that day you'd think i'd be coming home with 30-35% but nope it was red near zero. i got the flowy emerald 16/512 and it is an otherwise STUPENDOUS phone. i have the violet s24 ultra and i still haven't even opened it from its shipping box yet despite the s24 ultra arriving first. i have no interest in using the s24 ultra.",
    #         "You just upgraded to a flagship maybe that's why. Op phones are good and give you a taste of flagships.",
    #         "Do you have the bug where if you go into a browser like chrome, Firefox, or YouTube, and then you go back home, then try going back into those apps they don't respond to scrolling for like 1-2 seconds?",
    #         "Well that's not a bug, my other phones did it too. It's an application issue tbh. Don't worry about it too much chief",
    #         "OnePlus 12 is the Worst Phone I've Ever Bought",
    #         "I owned this phone for 90 minutes and I'm sending it back. I have had a smart phone since the Palm 700p and the Pre, then I've had Android since the HTC Evo 4G. I have never returned a phone that I can remember, and certainly not this fast. I used OnePlus for about 5 years and left for the Pixel 7 Pro because of a number of small gripes on my OnePlus phone at the time (8T? I can't remember) that finally made me willing to try someone else. My Pixel 7 Pro is great except Gmail crashes constantly. I've factory reset, replaced the phone, contacted Gmail Support (laughable, they don't really exist)... nothing works. So I thought I'd try OnePlus again. Here is why I've never hated a phone more than this:\nThe deal-breaker for me was the X at the bottom of the notification drawer at all times. It will clear all of your notifications, which is the nuclear bomb that I never drop. I don't believe anyone reading this is any different: if you want to clear notifications, don't you swipe away individual apps? On Pixel, the option to clear all notifications can only be accessed if you scroll to the bottom of your notifications and click to the side. The X on the OP12 is right where I would put my thumb to close the notifications. No way to remove this. I don't know how often I'll hit this if I own this phone for a few years, but I'm sure as hell not sticking around to find out. It's also just incredibly unintuitive. If you were going to close your notifications after they're open, wouldn't you go to the bottom-middle of the screen to swipe up? Just a stupid, stupid place to put the \"clear everything\" button.\nRemoving icons on your home screen requires a long press, then press Remove, then confirm. The \"long press and drag to the top to remove\" on every other Android phone is perfect. What made OP think this was anything less than perfect? Also, why the f*** is there a confirm option? I'm just removing it from my home screen. I can get it back stupidly easily if I want. And the idea that someone would \"accidentally\" long press AND click remove ever - much less often enough to make a \"confirm\" necessary or preferable - is stupid. Terrible.\nOne 4 apps wide on the app tray. Just dumb. Not configurable. Shit like this was ALWAYS configurable on OP devices before. Why would you not allow that? It has to be the easiest of UI options to add. And using the alphabet on the side is not a replacement. If I want to get to YouTube at the bottom of the list, I have to hold the phone in an extremely precarious way to be holding the phone with one hand while getting my thumb all the way to the Y. I would MUCH rather just scroll through the apps, which is significantly easier if there are 30 apps per screen versus 24.\nRead more",
    #         "Sorry for your experience but this literally brought smile to my face. After reading \"worst phone ever\" I was expecting some big issues, but these are all hilariously minor and subjective lol.",
    #         "This is the worst review/ user experience I have ever read.",
    #         "I came from a Pixel 7 Pro, and I have no issues with this minor stuff, but hey, to each their own",
    #         "The most minor stuff I've ever seen... Didn't list any of the pros or weighed them with the cons. Check my post on the Honor magic 5 pro...",
    #         "Made my day this post just ordered mine lol",
    #         "You may have an issue, not sure it's the phone though mate.",
    #         "I never thought i would have gotten 2014 youtube clickbaited by a Reddit title lmao. I came to this post expecting major issues and drama, but this was what i got? Disappointing lol",
    #         "Bruh you know almost all the things you've listed are just things that you need to get used to?. You'll experience this kind of stuff with every smartphone with every different version of customized Android you'll try.. If you're not willing to learn these small things just stick with the Pixel lineup, don't say that the \"OP 12 is the worst phone ever\" for these reasons lmao",
    #         "The 1. Dealbreaker you said exists in every android phone.There's an X to remove all notifications.This was painful to read man.",
    #         "The OnePlus 12 is very disappointing. I would even call it trash.",
    #         "Such a shame. I'm coming from a S21 Ultra, and this phone blows it out of the water in the battery department and brightness.\nEverything else is hot garbage.\nThe worst part is the power of the phone. Yes it's powerful blah blah.\nTyping, a very low power activity, lags. Bruh.\nReddit takes 10 seconds to load posts, then another ten seconds to load comments. Clearing cache helped for a couple hours, then back to terrible.\nChrome is slow. I ran a browser bench and got a 52 or so. My S21 Ultra got 69. That has a third of the hardware power. Chrome beta helped, with a score of 140. Yet the iPhone 15 pro max will get around 430.\nBlame the os or whatever, it stands that this is the most disappointing phone of the flagships.\nAny help would be appreciated.",
    #         "I had the Op12 for over a month now and didn't notice any lag in any app.This phone is snappy and fast.I find that the only drawback is the lack of customization in certain areas like the Lock screen...",
    #         "What the hell are you talking about? I came from an s22 ultra and the OnePlus 12 is fucking amazing it beats theses shitty \"ultra\" phones all day. You don't know what you are talking about.",
    #         "Why do people make shit posts like these?. Have you considered that you may have been unlucky enough to have a faulty device?. The overall tone of your post makes me believe you don't need help but rather an exorcism.",
    #         "Are you sure you didn't get a Oneplus 1 or 2 and not a 12?",
    #         "Regarding the Chrome score, it's a known \"issue\" that the browser benchmark is slow, as OnePlus tends to limit the power of chrome based browsers. Can you feel that the phone is slow even with ~70 score in real world usage? No. When it comes to phones nowadays, a benchmark score with the most recent and powerful CPUs doesn't mean anything as long as it's above a certain minimum.. I don't know what you're talking about with the keyboard lagging. I had it for a month now, it didn't lag even once.. For me Reddit takes 1-2 seconds to load the posts, and 1 second or less to load the comments. Absolutely no problem there.. Since 99% of the users have the same experience as I do, maybe it's your device that's faulty, don't you think? 😅. So don't write that \"the phone is trash\" in the title just for clout lol",
    #         "I've had some weird glitches on some apps like ig that won't allow me to post but that is about it. The best part by far is the charging. It's a complete non issue for this phpne.",
    #         "WTF did OP smoked before writing this post?",
    #         "How bad is OnePlus 12's camera?",
    #         "Every reviewer is praising OnePlus 12 apart from its camera performance. People who have used flagships like iphone 13/14 pro max and S23/S24 ultra, how bad is the image and video quality relative to those? Also how bad is 12r's relative to 12, if you've used both.",
    #         "op12's cameras are pretty decent by any standard.. idk what you're on about!!",
    #         "Thing is, most reviewers need to find something negative, but they dont want to be too negative (as that would mean they get banned from reviewing certain companies products) so they often find a common ground to bash one small feature. In OnePlus' case they are fairly known to have a lackluster camera (while they have taken huge steps on both 11 and 12) so it's an easy target. The key thing to note though is, if it's just one feature getting bashed it's generally a good product and people are struggling to find more stuff. Like when I bought my latest car, all reviewers were bashing ONE button in the center console and that's a button I've basically never really used in the 2 years I've had my car now.",
    #         "See you can never believe what everyone says, nowadays most of the phone's cameras are very good. You will not use multiple phones at the same time and I believe the price in which you're gonna get 12 will surely meet your expectations which should be right in the first place. Your question \"how bad\" just reflects that you've already made your mind and is just looking for validation here, no offence man but you should definitely use the phone's camera before making a judgement, what do even mean to say in the question, you're saying everyone is praising it and then you're asking how bad it is!!",
    #         "This! People forget the price range and objectively start comparing camera quality. Why not compare with a DSLR then. I don't own an OP12 but have seen the pictures clicked on one of my friend's OP 12. The quality is very good considering the price.",
    #         "It's really really good actually. Before I bought I also saw the reviews and they all said that it's not too great all that but when I bought it I was pleasantly surprised. That 3x lens is amazing.",
    #         "Good enough. Just not Pixel, Galaxy S and iPhone level, which should be enough for most people.. Heck in a side by side comparison some shots from a 12 might be better, but it's all personal preference",
    #         "Never had this good camera. So in my opinion it is really great.. Maybe there are better ones, but I'm happy.",
    #         "The camera is quite decent, but the hdr in mixed light conditions is.... Not great. Took some pictures of my wife which was back-lit, and she looked like a ghost with a halo.. It's good for 90+% of the cases I'd say. But it lacks in those last few %",
    #         "Uh, again a comparison with S23 ? I had all versions and the OP12 kills all of them in photography. Halo ?! That's an Samsung issue, doesn't happen on OP at all. It's actually only better in videography. But most people like heavily processed images more than the relatively natural the OP12 is shooting. I switched mainly because of this since i really disliked the algorithm Samsung uses. Just look at the sensor size and what kind of it is used on OP compared to Samsung. You can actually only complain about UI related stuff but not it's hardware and photo quality.",
    #         "It's not bad at all. It's an 800$ phone, and the camera is the one of a 1000$ ish phone, so it's actually really good. Of course if you want to buy your phone exclusively for the camera which is weird, take a Samsung, even if it's way more expensive.. In the 12r, the main camera is basically the only useful one"
    #     ]
    # product = Mouse(name='Oneplus 12', reddit_comments=comments)
    # product = ai.analyse_product(product)
    # print(product)
    
    reviews = '''
        The OnePlus 12 is an off-the-beaten-path flagship that goes spec for spec against its top rivals. Moreover, its 5,000mAh battery charges faster than most: It goes from 0% to 100% in just 38 minutes with the included 80W charger.
        A top-tier processor, super-fast charging, and a reasonable price make the OnePlus 12 an ideal Android phone for power users who don't want to spend too much.
        THE BOTTOM LINE
        With an impressive display, long battery life, speedy charging, and premium performance, the OnePlus 12 offers most of the features found on other flagship phones for a more affordable price.
        The OnePlus 12 (starting at $799.99) carries over many of the things we liked about last year's 11 5G and Open and improves upon them across the board. Its fast and vivid display, extra-long battery life, rapid wireless charging, and blazing performance make it a compelling alternative to flagship Android phones like the $899 Google Pixel 8 Pro and the $999 Samsung Galaxy S24+. The OnePlus 12 is well worth considering if you're looking to spend $100 to $200 less than either of those handsets, but it's not a clear-cut winner as it falls behind slightly in a few key areas.
        With loads of power, epic battery life, lightning-fast charging, and a solid camera, the OnePlus 12 almost has it all—at a lower price than the competition. That said, both the Galaxy S24 and the Pixel 8 have even better cameras, higher IP ratings, faster 5G, longer support commitments, and more AI-based features. If you place a high value on any or all of those features, you should consider spending more to get them, especially since Google and Samsung now offer such long-term support. Still, the OnePlus 12 covers far more than the basics, making it easy to recommend if you're looking for a flagship phone that's closer to a midrange price.
        The OnePlus 12 returns to the OnePlus roots as a flagship killer. This is a phone with excellent performance and the important features to challenge the expensive, premiere flagship phones, at a lower price. 
        ✅ You want a phone that looks cool: Are you bored with metal slabs? So is OnePlus, and the OnePlus 12 in either emerald green or a sparkly black finish will stand out from the crowd in the best way. 
        Design: I wish it were more durable, but I can't ask for the OnePlus 12 to be more beautiful, because it's truly a stunning phone that stands out from the pack the way formal attire stands out from a crowd in cocktail dress. 
        ✅ You need long battery in a hurry: The OnePlus 12 doesn't just have better battery life than the competition, it also charges faster. It even comes with a fast charger in the box, a rarity these days. 
        Display: OnePlus 12 takes on the best phones you can buy with a big, bright screen that is super-sharp, even more sharp than the iPhone 15 Pro Max. It even keeps the curve that Samsung abandoned, and it looks all the better for it. 
        If you're considering the OnePlus 12, you should buy it, because OnePlus knows its audience well, and this phone was made for your needs. It's the coolest-looking phone in a long time, maybe ever, while others are boring metal slabs. You'll get better battery life, faster charging, and a brighter screen, all on a phone that costs hundreds less than the competition's Ultra and Pro models. OnePlus makes some sacrifices, but they might not matter to you, and its winning design plus no-nonsense software makes it the coolest smartphone you can buy at any price.
        The OnePlus 12 is cool, there is no doubt about it. It looks gorgeous, and OnePlus has somehow managed to set itself apart from the slew of slabs that clutter store shelves with one of the sweetest color options I've ever seen on a phone, along with a design that is uncompromising and polished. 
        Just like the coolest people, the OnePlus 12 is fun and flashy and hides its weaknesses where you can't see them. It's the best player in a scoring position, but it can't play every role on the field. 
        The OnePlus 12 tries to play the smartphone game as the so-called 'flagship killer,' which is a phone that costs much less than the best Samsung Galaxy or best Apple iPhone, but still gives you the best features of those more popular handsets. 
        In many respects, it's victorious, especially when you compare the OnePlus 12 to competitor phones that actually cost the same. If the OnePlus 12 is almost good enough to take on the Galaxy S24 Ultra, it's more than enough to challenge the Galaxy S24, which is a bit more expensive. If the Pixel 8 Pro has a tough new competitor, the Pixel 8, at the same price, is no competition at all for the OnePlus 12.

        The OnePlus 12 has amazing performance, good enough to go toe-to-toe with the latest iPhone 15 Pro in games and some productivity tasks. It has cameras that produce excellent images; in some cases these photos are more compelling than the Galaxy S24 Ultra and our other best camera phones. 
        In other words, if you go for the OnePlus 12 instead of that other phone you were considering, you won't feel like you're missing out. You get top-level performance, amazing photography, and battery life that lasts for days. You also get some cool features you can't find elsewhere, like super-fast charging, and even an IR blaster that can change the channel on your TV. 
        For the price, the OnePlus 12 is a stellar phone that exceeds expectations. If that makes you a little suspicious, you're right to raise an eyebrow. What's missing are some of the same aspects OnePlus has omitted before, but now these features may be more important than ever. 
        For one thing, the OnePlus 12 isn't as durable as the Samsung Galaxy S24 Ultra or the iPhone 15 Pro, not even close. Between the iPhone 15 Pro's titanium frame and the new Gorilla Armor glass on the Galaxy Ultra, OnePlus won't stand up to abuse like its rivals.'''
    product = Mouse(name='Oneplus 12', description=reviews)
    ai.summarise_reviews(product)
    print(product)
    
if __name__ == "__main__":
    main()